# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-dns-delegated
  description: '    This component is responsible for provisioning a DNS zone which manages subdomains delegated from a DNS zone in the primary DNS account'
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component








